export type TooltipPosition = 'top' | 'bottom' | 'left' | 'right' | 'center';

export interface TourStep {
  id: string;
  route: string;
  search?: string;
  tourId: string; // matches data-tour="..." attribute on target element
  title: string;
  description: string;
  position: TooltipPosition;
  pageLabel: string; // shown in progress indicator
  icon: string; // emoji icon
}

export const supervisorSteps: TourStep[] = [
  // ── Welcome ───────────────────────────────────────────────────────────────
  {
    id: 'welcome',
    route: '/',
    tourId: 'sidebar-brand',
    title: 'Welcome to AttendanceOS 👋',
    description: 'This quick tour walks you through every feature in your system. Use the arrows or keyboard ← → to navigate. Click anywhere outside to skip.',
    position: 'right',
    pageLabel: 'Welcome',
    icon: '🚀',
  },

  // ── Today (dashboard + live roster) ───────────────────────────────────────
  {
    id: 'kpi-grid',
    route: '/',
    tourId: 'kpi-grid',
    title: 'Today\'s headcount',
    description: 'Expected, present, absent, on break, and attendance percentage. Refreshes every 60 seconds and updates live via WebSocket when workers scan.',
    position: 'bottom',
    pageLabel: 'Today',
    icon: '📊',
  },
  {
    id: 'btn-refresh',
    route: '/',
    tourId: 'btn-refresh',
    title: 'Manual refresh',
    description: 'Reload all Today data immediately without waiting for the auto-refresh cycle.',
    position: 'bottom',
    pageLabel: 'Today',
    icon: '🔄',
  },
  {
    id: 'panel-alerts',
    route: '/',
    tourId: 'panel-alerts',
    title: 'Requires action',
    description: 'Exceptions that need attention: absent workers, long breaks, pending corrections. Click an item to filter the roster or open the corrections queue.',
    position: 'left',
    pageLabel: 'Today',
    icon: '🔔',
  },
  {
    id: 'shift-status',
    route: '/',
    tourId: 'shift-status',
    title: 'Shift status',
    description: 'Capacity, present headcount, and variance for the active shift — pulled from your configured shifts.',
    position: 'left',
    pageLabel: 'Today',
    icon: '🕐',
  },
  {
    id: 'panel-activity',
    route: '/',
    tourId: 'panel-activity',
    title: 'Recent events',
    description: 'Latest check-ins, check-outs, and breaks across the facility with timestamp and capture method.',
    position: 'left',
    pageLabel: 'Today',
    icon: '⚡',
  },
  {
    id: 'input-search',
    route: '/',
    tourId: 'input-search',
    title: 'Search roster',
    description: 'Filter the workforce table by name, employee ID, or department.',
    position: 'bottom',
    pageLabel: 'Today',
    icon: '🔍',
  },
  {
    id: 'filter-bar',
    route: '/',
    tourId: 'filter-bar',
    title: 'Status filter',
    description: 'Narrow the roster to checked in, on break, checked out, or absent workers.',
    position: 'bottom',
    pageLabel: 'Today',
    icon: '🎯',
  },
  {
    id: 'worker-table',
    route: '/',
    tourId: 'worker-table',
    title: 'Workforce roster',
    description: 'Live status for every worker: department, last event, duration. Duration turns red when a break exceeds 20 minutes.',
    position: 'top',
    pageLabel: 'Today',
    icon: '👥',
  },

  // ── Worker Directory ──────────────────────────────────────────────────────
  {
    id: 'btn-add-worker',
    route: '/workers',
    tourId: 'btn-add-worker',
    title: 'Add New Employee',
    description: 'Opens the full enrollment form. Fill in name, employee code, department, shift assignment, daily wage, and contact details. Auto-generates a unique employee code.',
    position: 'bottom',
    pageLabel: 'Worker Directory',
    icon: '➕',
  },
  {
    id: 'btn-view-toggle',
    route: '/workers',
    tourId: 'btn-view-toggle',
    title: 'Grid & Table Views',
    description: 'Switch between a visual photo card grid and a dense data table. Grid view is great for face recognition; table view for bulk data review.',
    position: 'bottom',
    pageLabel: 'Worker Directory',
    icon: '⊞',
  },
  {
    id: 'input-worker-search',
    route: '/workers',
    tourId: 'input-worker-search',
    title: 'Search Your Roster',
    description: 'Find any worker by name, employee code, department, or role. Works across all active employees instantly.',
    position: 'bottom',
    pageLabel: 'Worker Directory',
    icon: '🔍',
  },
  {
    id: 'btn-edit-worker',
    route: '/workers',
    tourId: 'btn-edit-worker',
    title: 'Edit Worker Profile',
    description: 'Update any worker detail: wage rate, overtime rate, shift assignment, email, and phone. Changes take effect immediately on the next salary calculation.',
    position: 'left',
    pageLabel: 'Worker Directory',
    icon: '✏️',
  },
  {
    id: 'btn-face-register',
    route: '/workers',
    tourId: 'btn-face-register',
    title: 'Biometric Enrollment',
    description: 'Register a worker\'s face for the AI kiosk. The camera modal captures 5 angles for robust recognition. Takes about 30 seconds and the worker is immediately active on the kiosk.',
    position: 'left',
    pageLabel: 'Worker Directory',
    icon: '📷',
  },
  {
    id: 'btn-grant-access',
    route: '/workers',
    tourId: 'btn-grant-access',
    title: 'Grant System Access',
    description: 'Promote a field worker to a Supervisor system account. Set their username, password, and role directly from this card. They can then log in and monitor their own team.',
    position: 'left',
    pageLabel: 'Worker Directory',
    icon: '🔑',
  },

  // ── Reports (attendance + payroll) ────────────────────────────────────────
  {
    id: 'report-calendar',
    route: '/reports',
    tourId: 'report-calendar',
    title: 'Date selector',
    description: 'Pick any date to load that day\'s attendance report. Historical data is retained permanently.',
    position: 'bottom',
    pageLabel: 'Reports',
    icon: '📅',
  },
  {
    id: 'btn-export-csv',
    route: '/reports',
    tourId: 'btn-export-csv',
    title: 'Export to CSV',
    description: 'Download attendance for the selected date: worker ID, punches, presence hours, and net work time.',
    position: 'bottom',
    pageLabel: 'Reports',
    icon: '⬇️',
  },
  {
    id: 'report-summary',
    route: '/reports',
    tourId: 'report-summary',
    title: 'Daily summary',
    description: 'Total workers, complete attendance, incomplete punches, and absent count for the selected day.',
    position: 'bottom',
    pageLabel: 'Reports',
    icon: '📋',
  },
  {
    id: 'report-table',
    route: '/reports',
    tourId: 'report-table',
    title: 'Attendance timeline',
    description: 'Each row is one worker\'s punch timeline. Missing events show as dashes; incomplete rows are flagged.',
    position: 'top',
    pageLabel: 'Reports',
    icon: '📑',
  },

  // ── Corrections ───────────────────────────────────────────────────────────
  {
    id: 'btn-new-correction',
    route: '/corrections',
    tourId: 'btn-new-correction',
    title: 'Submit a Correction',
    description: 'Opens the correction form. Select the worker, choose the event type (Check In / Out / Break), provide the wrong and corrected timestamps, and give a reason. All submissions need admin approval.',
    position: 'bottom',
    pageLabel: 'Corrections',
    icon: '📝',
  },
  {
    id: 'correction-card',
    route: '/corrections',
    tourId: 'correction-card',
    title: 'Correction Request Card',
    description: 'Each card shows the worker name, event type, original time (struck through in red) vs. corrected time (in green), the reason, who requested it, and when.',
    position: 'top',
    pageLabel: 'Corrections',
    icon: '🗃️',
  },
  {
    id: 'btn-approve',
    route: '/corrections',
    tourId: 'btn-approve',
    title: 'Approve & Apply',
    description: 'Administrators only. Clicking this immediately writes the corrected attendance event to the database and creates an immutable audit log entry. The change is instant.',
    position: 'top',
    pageLabel: 'Corrections',
    icon: '✅',
  },
  {
    id: 'btn-reject',
    route: '/corrections',
    tourId: 'btn-reject',
    title: 'Reject Correction',
    description: 'Marks the correction as rejected. The original attendance record is untouched. An audit log entry records who rejected it and when.',
    position: 'top',
    pageLabel: 'Corrections',
    icon: '❌',
  },

  // ── Payroll (Reports tab) ─────────────────────────────────────────────────
  {
    id: 'salary-month',
    route: '/reports',
    search: '?tab=payroll',
    tourId: 'salary-month',
    title: 'Pay period',
    description: 'Select month and year. Payroll is computed from verified attendance, shift rates, and overtime rules.',
    position: 'bottom',
    pageLabel: 'Payroll',
    icon: '🗓️',
  },
  {
    id: 'btn-download-payroll',
    route: '/reports',
    search: '?tab=payroll',
    tourId: 'btn-download-payroll',
    title: 'Export payroll',
    description: 'Download CSV with worker ID, days present, base salary, OT hours, OT pay, and total payout.',
    position: 'bottom',
    pageLabel: 'Payroll',
    icon: '📤',
  },
  {
    id: 'payroll-table',
    route: '/reports',
    search: '?tab=payroll',
    tourId: 'payroll-table',
    title: 'Per-worker breakdown',
    description: 'Expand any row to see daily hours for the month. Overridden days are highlighted.',
    position: 'top',
    pageLabel: 'Payroll',
    icon: '📊',
  },
  {
    id: 'payroll-override',
    route: '/reports',
    search: '?tab=payroll',
    tourId: 'payroll-override',
    title: 'Hour override',
    description: 'Admins: click a day cell in the expanded view to enter corrected hours. Changes save immediately and appear in the total.',
    position: 'top',
    pageLabel: 'Payroll',
    icon: '⚙️',
  },
];

// Admin gets all supervisor steps PLUS these additional ones
export const adminOnlySteps: TourStep[] = [
  // ── Audit Logs ────────────────────────────────────────────────────────────
  {
    id: 'audit-search',
    route: '/audit',
    tourId: 'audit-search',
    title: 'Search the Audit Trail',
    description: 'Filter the full system event log by actor name, action keyword, or target resource. Results update in real-time as you type — with 400ms debounce for performance.',
    position: 'bottom',
    pageLabel: 'Audit Logs',
    icon: '🔍',
  },
  {
    id: 'audit-export',
    route: '/audit',
    tourId: 'audit-export',
    title: 'Export Audit Log',
    description: 'Download the complete audit log as a CSV with all columns: Timestamp, Actor, Action, Target, Details, and IP Address. Required for compliance and security reviews.',
    position: 'bottom',
    pageLabel: 'Audit Logs',
    icon: '📥',
  },
  {
    id: 'audit-table',
    route: '/audit',
    tourId: 'audit-table',
    title: 'Immutable Audit Log',
    description: 'Every action in the system is logged here permanently — who did it, what they did, the exact timestamp, and the originating IP address. Records cannot be modified or deleted.',
    position: 'top',
    pageLabel: 'Audit Logs',
    icon: '🔒',
  },

  // ── Settings ──────────────────────────────────────────────────────────────
  {
    id: 'settings-nav',
    route: '/settings',
    tourId: 'settings-nav',
    title: 'Settings Sections',
    description: 'Navigate between 13 configuration sections: Profile, Operational Rules, Shifts, Permissions, AI Kiosk, Biometric Privacy, Security, Notifications, Payroll Exports, Integrations, Audit, System Info, and Danger Zone.',
    position: 'right',
    pageLabel: 'Settings',
    icon: '⚙️',
  },
  {
    id: 'settings-permissions',
    route: '/settings',
    tourId: 'settings-permissions',
    title: 'Supervisor Permissions',
    description: 'Fine-tune exactly what Supervisors can do: view salary data, delete workers, approve corrections, manage shifts. Each toggle is applied in real-time, no restart needed.',
    position: 'right',
    pageLabel: 'Settings',
    icon: '🛡️',
  },
  {
    id: 'settings-security',
    route: '/settings',
    tourId: 'settings-security',
    title: 'Security Controls',
    description: 'Force all connections to HTTPS, configure session timeout windows, and rotate JWT secrets. The HTTPS redirect is applied globally to every API request when enabled.',
    position: 'right',
    pageLabel: 'Settings',
    icon: '🔐',
  },
  {
    id: 'settings-danger',
    route: '/settings',
    tourId: 'settings-danger',
    title: 'Danger Zone',
    description: 'Factory reset, attendance data purge, and biometric descriptor scrubbing. Every action requires typing a confirmation code and is logged permanently in the audit trail.',
    position: 'right',
    pageLabel: 'Settings',
    icon: '⚠️',
  },
];

export const adminSteps: TourStep[] = [...supervisorSteps, ...adminOnlySteps];
