/** Default system settings — single source of truth for backend. */
export const SETTINGS_DEFAULTS: Record<string, string> = {
  teaBreakDuration: '15',
  lunchBreakDuration: '30',
  breakOvertimeAlert: '5',
  standardWorkHours: '8',
  overtimeThreshold: '9',
  deductBreaks: 'true',
  perm_supervisor_salary_view: 'true',
  perm_supervisor_worker_view: 'true',
  perm_supervisor_worker_delete: 'false',
  perm_supervisor_correction_approve: 'true',
  ai_threshold: '0.6',
  gracePeriod: '10',
  earlyCheckout: '15',
  maxConsecutiveDays: '6',
  midnightAlgo: 'true',
  autoBreakLog: 'false',
  weekendMultiplier: '1.5',
  holidayMultiplier: '2.0',
  nightDiffRate: '1.25',
  nightDiffStart: '22:00',
  weekendOT: 'true',
  holidayPay: 'true',
  nightDiff: 'false',
  holiday_calendar: '[]',
  shiftBufferTime: '15',
  minRestBetweenShifts: '8',
  shiftSwapApproval: 'true',
  autoAssignOverflow: 'false',
  shiftCapacityAlertPct: '80',
  shiftCapacityAlerts: 'true',
  perm_supervisor_enroll_workers: 'true',
  perm_supervisor_manage_shifts: 'false',
  perm_supervisor_export_payroll: 'false',
  perm_supervisor_view_analytics: 'true',
  perm_supervisor_send_notifications: 'false',
  perm_supervisor_manage_holidays: 'false',
  perm_supervisor_view_audit: 'true',
  perm_supervisor_kiosk_config: 'false',
  ai_model: 'ssd_mobilenet',
  ai_scan_interval: '800',
  ai_auto_retry: '3',
  ai_model_cache_mb: '128',
  ai_landmarks: 'true',
  ai_liveness: 'false',
  ai_rfid_fallback: 'true',
  ai_multiface_alert: 'false',
  kiosk_camera_res: '720p',
  kiosk_idle_timeout: '30',
  kiosk_ir_mode: 'false',
  kiosk_offline_mode: 'true',
  bio_enrollment_samples: '5',
  bio_reenrollment_days: '180',
  bio_retention_days: '365',
  bio_auto_delete: 'true',
  bio_audit_access: 'true',
  bio_supervisor_enroll: 'true',
  sec_jwt_expiry: '480',
  sec_refresh_expiry: '10080',
  sec_lockout_attempts: '5',
  sec_lockout_duration: '15',
  sec_password_min_len: '12',
  sec_password_expiry: '90',
  sec_mfa_enabled: 'false',
  sec_ip_whitelist: 'true',
  sec_session_log: 'true',
  sec_force_https: 'true',
  sec_cors_origin: '*',
  sec_ip_list: '192.168.1.0/24',
  sec_kiosk_token: '',
  notif_channel: 'webhook',
  notif_email: '',
  notif_sms: '',
  notif_webhook_url: '',
  notif_digest_freq: 'daily',
  notif_quiet_hours: 'true',
  notif_quiet_start: '22:00',
  notif_quiet_end: '06:00',
  notif_overtime_alert: 'true',
  notif_missed_punch: 'true',
  notif_login_failed: 'true',
  notif_enrollment: 'true',
  notif_payroll_ready: 'true',
  notif_low_capacity: 'false',
  notif_capacity_pct: '80',
  payroll_format: 'csv',
  payroll_period: 'biweekly',
  payroll_rounding: 'nearest_15',
  payroll_currency: 'USD',
  payroll_tax_rate: '22',
  payroll_deduct_breaks: 'true',
  payroll_include_overtime: 'true',
  payroll_encrypt: 'false',
  payroll_auto_export: 'false',
  payroll_export_time: '07:00',
  sys_backup_freq: 'daily',
  sys_backup_retention: '30',
  sys_log_level: 'warn',
  sys_compression: 'true',
  sys_rate_limit_window: '15',
  sys_rate_limit_max: '100',
  sys_db_url: '',
  audit_retention_days: '730',
  audit_immutable: 'true',
  audit_gdpr_mode: 'true',
  audit_export_enabled: 'true',
  audit_data_residency: 'on-premise',
  mobile_sync_interval_sec: '120',
  mobile_offline_queue_max: '500',
  mobile_heartbeat_interval_sec: '60',
  mobile_offline_timeout_min: '5',
  mobile_ble_enabled: 'true',
  mobile_ble_broadcast_name: 'FAMS-Kiosk',
  mobile_tts_enabled: 'true',
  mobile_pin_override_enabled: 'true',
  mobile_auto_sync_on_wifi: 'true',
  mobile_face_model: 'mobilefacenet',
};

export function mergeSettings(fromDb: Record<string, string>): Record<string, string> {
  return { ...SETTINGS_DEFAULTS, ...fromDb };
}

export function settingBool(settings: Record<string, string>, key: string, defaultVal = false): boolean {
  const v = settings[key];
  if (v === undefined) return defaultVal;
  return v === 'true';
}

export function settingNum(settings: Record<string, string>, key: string, defaultVal: number): number {
  const n = Number(settings[key]);
  return Number.isFinite(n) ? n : defaultVal;
}
